/* Generated By:JJTree: Do not edit this line. ASTCreateTableStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTCreateTableStatement extends SimpleNode {
  public ASTCreateTableStatement(int id) {
    super(id);
  }

  public ASTCreateTableStatement(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fc91bb6a1f6f700984fe99d29629fb77 (do not edit this line) */
