/* Generated By:JJTree: Do not edit this line. ASTCommonTableExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTCommonTableExpression extends SimpleNode {
  public ASTCommonTableExpression(int id) {
    super(id);
  }

  public ASTCommonTableExpression(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=772b57cea11234ee6c0423a062dcd9e6 (do not edit this line) */
