/* Generated By:JJTree: Do not edit this line. ASTComparisonExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTComparisonExpression extends SimpleNode {
  public ASTComparisonExpression(int id) {
    super(id);
  }

  public ASTComparisonExpression(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cac2f5ceaa01098e2056a8d1e84e6646 (do not edit this line) */
