/* Generated By:JJTree: Do not edit this line. ASTDropTableStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTDropTableStatement extends SimpleNode {
  public ASTDropTableStatement(int id) {
    super(id);
  }

  public ASTDropTableStatement(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5c6d1d035b76979265230f1d45b1277a (do not edit this line) */
