/* Generated By:JJTree: Do not edit this line. ASTDropIndexStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTDropIndexStatement extends SimpleNode {
  public ASTDropIndexStatement(int id) {
    super(id);
  }

  public ASTDropIndexStatement(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c7930d12e34271c8390e22796297cec (do not edit this line) */
