/* Generated By:JJTree: Do not edit this line. ASTLimitClause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTLimitClause extends SimpleNode {
  public ASTLimitClause(int id) {
    super(id);
  }

  public ASTLimitClause(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b7fa0fc2023f2e2f3b63222ae43730f3 (do not edit this line) */
