/* Generated By:JJTree: Do not edit this line. ASTRollbackStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTRollbackStatement extends SimpleNode {
  public ASTRollbackStatement(int id) {
    super(id);
  }

  public ASTRollbackStatement(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d9f6aa5bd2ab4eefb0dd2370d8511de (do not edit this line) */
