/* Generated By:JJTree: Do not edit this line. ASTSelectColumn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTSelectColumn extends SimpleNode {
  public ASTSelectColumn(int id) {
    super(id);
  }

  public ASTSelectColumn(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f42b9bdb54b32e079439ad81bcca49d0 (do not edit this line) */
