/* Generated By:JJTree: Do not edit this line. ASTSelectClause.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTSelectClause extends SimpleNode {
  public ASTSelectClause(int id) {
    super(id);
  }

  public ASTSelectClause(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb92d4c7bd045ac61deaad44f22a1cf3 (do not edit this line) */
