/* Generated By:JJTree: Do not edit this line. ASTUpdateStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.csfundamental.database.cli.parser;

public
class ASTUpdateStatement extends SimpleNode {
  public ASTUpdateStatement(int id) {
    super(id);
  }

  public ASTUpdateStatement(RookieParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9e50f82003f6f3ed45173d8d1f218a0 (do not edit this line) */
